### ISSUE TITLE
Campo de Atividade Fiscal Extremamente Confuso

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#11]
Eu acho essa opção extremamente complicada para um usuário leigo.

![fcunmgj8sfcrccqdvbmt6w](https://user-images.githubusercontent.com/19148962/36540783-6bd400ea-17ba-11e8-8a98-ff8547f5f9cf.png)

Sem mencionar que não fica claro que é possível adicionar um valor específico dentro do produto. Nem o que exatamente esses códigos significam e onde o usuário deve pegar essa informação.

Sugiro mudar os nomes para algo mais comum, ou adicionar links para página de documentação com uma explicação mais clara, ensinando ao usuário onde ele deve pegar esse tipo de informação.

Isso vai evitar que usuários leigos não deixe o campo vázio ou adicionem informações erradas.

**Comment by gblmarquez** [comment]
@renatonascalves resolvendo os bugs, vamos avaliar com alguns clientes o que ficaria mais simples para eles.

A principio, traduzindo os campos já deve ajudar, até porque geralmente nosso sucesso do cliente, apoia na configuração do plugin.

**Comment by renatonascalves** [comment]
@gblmarquez Já decidiu como irá fazer aqui?

**Comment by gblmarquez** [comment]
@renatonascalves segue a descrição de cada campo

**Atividade Fiscal (Global)** para **Configurações de Serviço para Nota Fiscal**

**CityServiceCode** para **Cód. Serviço na Cidade (CityServiceCode)**
Código de Serviço na Cidade, este é o código que identificará para a prefeitura qual o serviço que está sendo prestado pela sua empresa.

**FederalServiceCode** para **Cód. Serviço Federal LC 116 (FederalServiceCode)**
Código de Serviço com base na Lei Federal (LC 116), este é o código federal que identifica para a prefeitura qual o serviço que está sendo prestado pela sua empresa.

**Descrição** para **Descrição do Serviço** 
Digite aqui a descrição que você deseja na nota fiscal, esta descrição deve explicar qual foi o serviço prestado entre outros detalhes. Peça ajuda a seu contador caso tenha dúvidas.

**Veja se tem algum lugar para colocar esse texto ai na página**
Caso tenha dúvidas sobre o que colocar nesses campos, peça ajuda para seu contador ou entre em contato com nossa equipe pelo suporte@nfe.io
