### ISSUE TITLE
Suporte a versão mais recente do WooCommerce

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#14]
Depois de atualizado, adicionar o suporte para a versão mais recente do plugin.

![screenshot_2](https://user-images.githubusercontent.com/19148962/36541052-6aeb658c-17bb-11e8-8bcb-bbe422e8bc97.jpg)

Isso irá passar mais confiança aos usuários quando forem fazer o download do plugin.

**Comment by gblmarquez** [comment]
Com certeza 👍
