### ISSUE TITLE
Informações NFe no Box de Pedidos

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#15]
Mostrar de forma rápida as informações do NFe.io.

![screenshot_3](https://user-images.githubusercontent.com/19148962/36541195-e1a53a9a-17bb-11e8-9151-a41d59f8cedf.jpg)

**Comment by gblmarquez** [comment]
@renatonascalves sugiro aqui colocarmos os dados:

- Status da Nota Fiscal (status)
- Número da Nota Fiscal (number)
- Código de Verificação (checkCode)
- Data da Emissão / Data do Cancelamento (issuedOn / cancelledOn)

Poderíamos depois avaliar se devemos mostrar dados relacionados a impostos, mas ai teríamos que validar com os clientes a necessidade.
