### ISSUE TITLE
Adicionar Status das Notas no Status do WooCommerce

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#16]
Essa é apenas uma sugestão.

Adicionar status das notas, emitidas, canceladas, etc.

![screenshot_1](https://user-images.githubusercontent.com/19148962/36541275-25f97936-17bc-11e8-9644-652af4d8f9a5.jpg)

**Comment by gblmarquez** [comment]
@renatonascalves boa sugestão, faz sentido colocarmos os seguintes contadores:
1. NFs Emitidas
2. NFs Canceladas
3. NFs com Erro
4. NFs em Processando

O que acha?

Como recebemos o webhook, fica fácil saber o status das NFs.
