### ISSUE TITLE
CTA da Página de Pedidos

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#17]
Na versão mais recente do WooCommerce, os CTA do plugin não aparecem mais. O WooCommece deixou a opções de fazer certas ações na página de edição do pedido.

O WooCommerce NFe irá também mudar nesse sentido ou irá recriar as CTA na página de pedidos?

![screenshot_2](https://user-images.githubusercontent.com/19148962/36541468-c21c01a8-17bc-11e8-9bb1-e4114b6917d8.jpg)

**Comment by renatonascalves** [comment]
Uma observação, essa recriação não é complexa. Apenas estou levantando uma decisão de UI que foi feita e se o plugin irá "no embalo" ou se irá manter o padrão anterior.

**Comment by gblmarquez** [comment]
@renatonascalves acredito que seja melhor nesse caso seguirmos os padrões de outros plugins, pois assim fica mais compatível com outras decisões.

**Comment by renatonascalves** [comment]
@gblmarquez Só para confirmar, as ações irão para dentro da página de edição do pedido, correto?

**Comment by gblmarquez** [comment]
Sim. É como os plugins estão sendo criados correto? Temos que seguir os padrões.

**Comment by gblmarquez** [comment]
Perfeito! Vamos seguir assim.
