### ISSUE TITLE
Mudar nome da aba nas configurações

### ISSUE THREAD

**Issue by gblmarquez** [nfe/woo-nfe#21]
Hoje temos a aba de configurações do NFE.io assim
![image](https://user-images.githubusercontent.com/367279/36633672-5b18bbdc-1978-11e8-9018-7124700ae271.png)

Devemos mudar o nome "Integração" para "Integração NFE.io"

**Comment by renatonascalves** [comment]
@gblmarquez Esse nome de cima não é possivel alterar. Essa é uma página padrão do WooCommece que mantem todas as integrações de uma loja.

Nós apenas extendemos essa funcionalidade com `WC_Integration`.

No seu exemplo, só existe apenas uma integração, mas em alguns sites, esse número pode ser maior. Exemplo: 

![integracao](https://user-images.githubusercontent.com/19148962/36634007-f2b491f6-197c-11e8-9659-1f594ca4a971.jpg)

Para ter uma aba específica/sozinha, precisamos recriar as configurações e integrações.

**Comment by gblmarquez** [comment]
@renatonascalves podemos mudar o "Integração WooCommerce NFE" para "Notas Fiscai (NFE.io)"

**Comment by gblmarquez** [comment]
@renatonascalves você sugere que tenhamos uma aba sozinhos? ou assim é o padrão de outros plugins?
