### ISSUE TITLE
Correção para a emissão manual

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#33]
Estava verificando se tinha informação do NFe. Quando o processo é manual, essas informações ainda não existe no sistema.

**Comment by renatonascalves** [comment]
@gblmarquez Acima estou adicionando um fix para corrigir a emissão de notas manuais na página de edição do pedido.

**Comment by gblmarquez** [comment]
@renatonascalves perfeito!

Só para confirmar esse IF está correto? Pois o status está "chumbado", se puder me explique o que estamos fazendo ali para confirmar se a lógica está correta.
https://github.com/nfe/woo-nfe/blob/1124c666e28bdc5bba3deda039f5fc3d744dec50/includes/frontend/class-frontend.php#L88

**Comment by renatonascalves** [comment]
^ Isso ai foi corrigido aqui: https://github.com/nfe/woo-nfe/commit/dcb11f9cfd80df56a01938b004a0f499470e8f18

@gblmarquez ^

**Comment by gblmarquez** [comment]
@renatonascalves Existe alguma forma de testar no ambiente do cliente antes de subir?

**Comment by renatonascalves** [comment]
@gblmarquez Sim! Manualmente! Segue: https://github.com/nfe/woo-nfe/archive/dev.zip

**Comment by renatonascalves** [comment]
@gblmarquez Corrigido:

1. não ter id de emissão 
2. status não for emitido ou cancelado
3. pedido com os dados de endereço estiver OK

A função `nfe_order_address_filled` também foi corrigida para ficar mais intuitiva e não causar confusão. :)

**Comment by renatonascalves** [comment]
@gblmarquez Dependência do status removida no commit acima.
