### ISSUE TITLE
Habilitar e desabilitar emissão na prefeitura

### ISSUE THREAD

**Issue by renatonascalves** [nfe/woo-nfe#43]
Em conversa com um cliente que usa o plugin, algo mencionado foi a opção de emissão no modo de desenvolvimento.

Atualmente, a pessoa precisa ir para o painel do NFe.io, em determinada empresa, para ativar a emissão na prefeitura.

Existe alguma API para ativar/desativar a emissão @gblmarquez? Assim, o cliente pode ativar e emitir notas no modo que escolher. A empresa selecionada é verificada na hora de ativar/desativar.

![off-on](https://user-images.githubusercontent.com/19148962/37477554-b529108a-2856-11e8-92de-16396f0b1dad.jpg)

**Comment by gblmarquez** [comment]
@renatonascalves é possível sim.

Para isso basta fazer uma atualização da empresa, seria o request PUT /v1/companies/{company_id}, passando os dados e atualizando o campo "environment": "production"
