### ISSUE TITLE
Problema ao instalar plugin

### ISSUE THREAD

**Issue by brunolprado** [nfe/woo-nfe#51]
Estou instalando meu plugin, tenho uma conta ativa e esse erro aparece no momento da ativação do plugin.

Fatal error: Can't use function return value in write context in /home/mogco806/public_html/metodogestalt.com.br/wp-content/plugins/woo-nfe/includes/admin/class-settings.php on line 234

**Comment by renatonascalves** [comment]
@brunolprado Está usando a versão master?

**Comment by brunolprado** [comment]
Estou usando a versão que está no site de wordpress e na sessão de plugins. https://br.wordpress.org/plugins/woo-nfe/

**Comment by renatonascalves** [comment]
@brunolprado Acredito que é um bug válido. Você está usando a versão do PHP 5.5 ou menor, correto?

Vou adicionar um fix para esse bug.

cc: @gblmarquez

**Comment by renatonascalves** [comment]
@gblmarquez Essa é uma boa oportunidade para adicionar o 'header' `Requires PHP: ` no readme do plugin.

Até agora, não pensamos em qual seria a versão mínima do PHP a ser usada. Suponho que seja a versão 5.4 pois o client-php suporta da versão 5.4 em diante.

Correto?

**Comment by gblmarquez** [comment]
@renatonascalves atualizamos a versão do PHP para 7.0 porém o erro persistiu.
Podemos sim colocar esse header, pois ajuda a evitar problemas.

**Comment by brunolprado** [comment]
Eu atualizei minha hospedagem para o php 7. Mas meu site acusa continuar utilizando a 5.4.45.

**Comment by renatonascalves** [comment]
@brunolprado Você precisa além de atualizar o PHP, mudar a versão do PHP. Se usa Cpanel, no painel deles existem essa opção. Atualizar a versão do PHP não é a mesma coisa de usar a versão que foi atualizada. :)

@gblmarquez Perfeito! Então, colocarei a versão 5.5. Vou precisar alterar algumas coisas no plugin para dá suporte a essa versão.

> atualizamos a versão do PHP para 7.0 porém o erro persistiu.

Pelo o que o Bruno falou acima, ele precisa usar a versão 7.0.

**Comment by brunolprado** [comment]
@renatonascalves Estou usando a versão 7.0 na hospedagem. Mas não sei se alterou no site.

**Comment by renatonascalves** [comment]
@brunolprado O site usa a versão que está ativa no servidor. Porém, o servidor pode ter mais de uma versão de PHP ativa. Recomendo vc se certificar qual é a versão ativa no painel do seu servidor.

**Comment by brunolprado** [comment]
Pessoal. Deu certo. Procurei um tutorial no suporte da minha hospedagem, e percebi que o problema é que eu não tinha selecionado a pasta do site para alterar o php. Agora sim consegui passar o site para o php 7.0, instalei o plugin e deu tudo certo. Muito obrigado @renatonascalves e @gblmarquez

**Comment by renatonascalves** [comment]
@brunolprado Disponha!

@gblmarquez Vou providenciar essa alteração! PR em breve!

**Comment by gblmarquez** [comment]
@renatonascalves podemos fechar issue e criar uma nova para colocar esse PR.
