### ISSUE TITLE
Código do Serviço Prestado da NFS-e inexistente.

### ISSUE THREAD

**Issue by brunolprado** [nfe/woo-nfe#55]
A emissão de nota está dando erro. Consta que não existe o código do serviço prestado, mas eu coloquei o mesmo código do CNAE.

[https://metodogestalt.com.br/wp-content/uploads/2018/05/registro.png](https://metodogestalt.com.br/wp-content/uploads/2018/05/registro.png)
[https://metodogestalt.com.br/wp-content/uploads/2018/05/config.png](https://metodogestalt.com.br/wp-content/uploads/2018/05/config.png)
[https://metodogestalt.com.br/wp-content/uploads/2018/05/erro.png](https://metodogestalt.com.br/wp-content/uploads/2018/05/erro.png)

**Comment by renatonascalves** [comment]
@gblmarquez Você poderia ajudar esse rapaz?

**Comment by gblmarquez** [comment]
@brunolprado 

Para resolver esse problema basta informar nos campos

- Código de Serviço Municipal o valor *5762* 
- Código de Serviço Federal pode deixar em branco

**Comment by brunolprado** [comment]
Deu certo.

Obrigado.
