### ISSUE TITLE
Endereço pendente

### ISSUE THREAD

**Issue by brunolprado** [nfe/woo-nfe#58]
Acontece muito do plugin não conseguir emitir a nota por falta de alguma informação no endereço, inclusive aquelas que são opcionais como bairro.

Normalmente eu tenho que completar esses campos de endereço com um "-" para que a nota possa ser emitida.

Um caso recente, o plugin acusa endereço pendente mesmo de um usuário que possui o endereço completo, sendo assim não consigo emitir a nota dela.

1- Como fazer para conseguir emitir essa nota?
2- É possível que o plugin não precise de todos os campos do endereço para evitar esse trabalho de conferência e edição?

**Comment by renatonascalves** [comment]
Bairro não é uma informação optional para emissão de nota. Assim, sem ele, o plugin irá exigir tal informação.

> 1- Como fazer para conseguir emitir essa nota?

Eu recomendo verificar no log por qual motivo a nota não emitida.

> 2- É possível que o plugin não precise de todos os campos do endereço para evitar esse trabalho de conferência e edição?

Sim! Nas configurações do WooCommerce NFe, existe a opção de exigir ou não o endereço na hora de emitir.
