### ISSUE TITLE
Feature Request: Mostrar link para a nota no site NFE.io

### ISSUE THREAD

**Issue by sidneydemoraes** [nfe/woo-nfe#62]
Enquanto __analista financeiro__, 
    Quero encontrar um link direto para a nota no site do NFE.io na ordem do WooCommerce 
    Para facilitar meu trabalho na hora de ver informações adicionais ou cancelar uma nota fiscal.

O local onde o link seria útil está marcado no print abaixo.
<img src="https://user-images.githubusercontent.com/696278/94828708-226c1b80-03e0-11eb-9a1a-10e7a1035653.png" 
width="600"></img>

O format do link seria algo como: `https://app.nfe.io/companies/<company_id>/service-invoices/<invoice_id>`

**Comment by gblmarquez** [comment]
@sidneydemoraes faz sentido algo assim, você consegue realizar a implementação?

**Comment by souzadavi** [comment]
Implementado com sucesso, por favor fechar essa issue.
