### ISSUE TITLE
Feature Request: impedir reemissão de nota fiscal

### ISSUE THREAD

**Issue by sidneydemoraes** [nfe/woo-nfe#63]
Enquanto __analista financeiro__,
    Quero ser impedido de emitir uma nova nota fiscal caso o pedido já tenha uma emitida
    Para evitar cobrança duplicada de impostos.

Conforme conversamos com o Gabriel, surgiu a hipótese de um chaveamento nas configurações do plugin permitindo ou não a reemissão. Atualmente, se realizarmos uma emissão de nota através do comando manual do plugin em um pedido que há tenha nota emitida, uma nova nota é emitida na prefeitura e, na visualização do woocommerce, continua constando os dados apenas da última nota emitida. 

Isso prejudica o processo de conciliação do financeiro e torna bem difícil a auditoria pra identificar qual pedido teve nota fiscal duplicada.

**Comment by gblmarquez** [comment]
@sidneydemoraes vc vai fazer a implementação?

**Comment by souzadavi** [comment]
Por favor fechar essa Issue, recurso implementado com sucesso!
