### ISSUE TITLE
atualização do plugin em relação ao wordpress

### ISSUE THREAD

**Issue by kitajoao** [nfe/woo-nfe#67]
de acordo com o nosso cliente, o plugin não está gerando o webhook para ser cadastrado na NFE.io.

**Comment by souzadavi** [comment]
@kitajoao saberia me informar qual dos webhooks não estão sendo cadastrado na NFE.io?

**Comment by kitajoao** [comment]
Segundo o cliente, o de acordo com essa imagem.

[image: image.png]




Em ter., 27 de out. de 2020 às 11:38, Davi <notifications@github.com>
escreveu:

**Comment by souzadavi** [comment]
Olá @kitajoao a imagem não apareceu. Poderia por gentileza confirmar essa informação? Obrigado.

**Comment by kitajoao** [comment]
Davi.

Segue a imagem.

![image](https://user-images.githubusercontent.com/51325916/98384588-b6a74f00-202c-11eb-9a8e-d95fc9e89e12.png)

**Comment by JoaoVictorLNacional** [comment]
esse problema foi corrigido,se acontecer de novo por favor nos comunique.

**Comment by souzadavi** [comment]
A correção esta no pull_request **
