### ISSUE TITLE
Duplicação da Emissão de Nota Fiscal

### ISSUE THREAD

**Issue by gblmarquez** [nfe/woo-nfe#68]
Estamos com um problema intermitente, em algum cenário de _racing condition_ no momento do gatilho da emissão da nota fiscal, seja via mudança do status ou mesmo usando a ação dentro do pedido para emissão da nota fiscal, duas ou mais solicitações são enviadas para a API da NFE.io.

Na analise que fizemos notamos que em todos os casos, sempre existe a Anotação no Pedido que indica que o processo de emissão foi solicitado mais de uma vez.

Acredito que esse problema se trata dessa linha
https://github.com/nfe/woo-nfe/blob/e7cbf51718e8ff4385583d9199e4f33c7277a862/includes/admin/class-api.php#L92

E que para resolvermos devemos fazer uma alteração na ordem em que o código é executado, veja na linha abaixo, que só é alterado os dados do pedido depois que a chamada para API é executada
https://github.com/nfe/woo-nfe/blob/e7cbf51718e8ff4385583d9199e4f33c7277a862/includes/admin/class-api.php#L109

Minha sugestão para resolver seria, no momento do gatilho para emissão da nota fiscal, alterarmos algum campo no pedido indicando que ele está em processamento, depois que essa alteração no pedido tenha sucesso então podemos realizar a requisição para a API da NFE.io. Sendo assim seria necessário ainda incluir uma condição que faça a verificação se o pedido já está em processamento, para evitar esse cenário.

**Comment by renatonascalves** [comment]
Existem três locais onde há solicitações de criação de notas. Seguem os três: https://github.com/nfe/woo-nfe/search?q=issue_invoice

Se entendi bem, você está dizendo que a API através da classe `NFe_ServiceInvoice` está solicitando duas vezes ao invés do método `issue_invoice` está sendo chamado duas vezes e criando duas solicitações de notas.

Se for a primeira situação, é preciso confirmar o que pode ter mudado no `client-php` para está solicitando duas vezes. Se for a segunda situação, é preciso verificar como as duas solicitações podem está sendo geradas dentro do WordPress.

Não lembro de ter encontrado esse error antes então pode ser que algo tenha mudado no WooCommerce. Precisa ser investigado.

**Comment by JoaoVictorLNacional** [comment]
esse problema foi corrigido,se acontecer de novo por favor nos comunique.
